# Base du language

Assignment la valeur 1 a la variable a
Cette variable est typé ici c'est un entier = integer = int

sdfsdf

In [2]:
a = 1
print(a)
print(type(a))

1
<class 'int'>


Il y adifférent type en python

In [3]:
b = 2.456
print(b)
print(type(b))

2.456
<class 'float'>


On peut effectuer des opérations sur ces variables
Notez le changement de type.

In [4]:
c = a+b
print(c)
print(type(c))


3.456
<class 'float'>


Gestion des chaines de carractères

In [6]:
s = 'hello'
print(s)
print(type(s))


hello
<class 'str'>


In [9]:
s2 =   "hel'lo"  
print(s2)

hel'lo


In [11]:
s3 = """youpi

éè $ ê


sdfsdfsdf
"""
print(s3)


youpi

éè $ ê


sdfsdfsdf



Opération sur str

In [13]:
s4 = s3+s2+s3
print(s4)


youpi

éè $ ê


sdfsdfsdf
hel'loyoupi

éè $ ê


sdfsdfsdf



Chaque variable est un object qui a des méthodes:

In [17]:
s4.upper()

"YOUPI\n\nÉÈ $ Ê\n\n\nSDFSDFSDF\nHEL'LOYOUPI\n\nÉÈ $ Ê\n\n\nSDFSDFSDF\n"

Formatage des str

In [19]:
s5 = 'ma variable est '+str(c)+' !'
s5


'ma variable est 3.456 !'

In [21]:
s6 = '3.56'
print(s6, type(s6))
f6 = float(s6)
print(f6, type(f6))

3.56 <class 'str'>
3.56 <class 'float'>


In [22]:
s5 = f'ma variable est {c} !'
s5

'ma variable est 3.456 !'

In [24]:
s5 = 'ma variable est {}'.format(c)
s5

'ma variable est 3.456'

Autre type util : bool et complex

In [28]:
flag1 = True
flag2 = False
flag3 = flag1 and flag2
print(flag3, type(flag1))


False <class 'bool'>


In [30]:
c = 50 + 50j
print(c, type(c))

(50+50j) <class 'complex'>


# Création d'un function

On peut créer des functions avec des variables en entrée et une variable de sortie.

Attention a l'indentation celà definit le **block**.

En python c'est 4 espaces.



In [40]:
def mon_add(a, b):
    c = a+b
    s = f'resultat: {a}+{b}={c}'
    return s


res = mon_add(5, 4)
print(res)


resultat: 5+4=9


In [38]:
aa = 3
bb = 77
res = mon_add(aa, bb)
print(res)


resultat: 3+77=80


Il peut y avoir plusieurs varibales de sortie.

In [43]:
def mon_add_bis(a, b):
    c = a+b
    s = f'resultat: {a}+{b}={c}'
    return s, c

res, res2 = mon_add_bis(5, 4)
print(res)
print(res2)


resultat: 5+4=9
9


Python permet d'avoir des variables facultatives.

In [47]:
def mon_add_ter(a, b, c=1, d=3):
    t = a+b+c+d
    s = f'resultat: {a}+{b}+{c}+{d}={t}'
    return s

res = mon_add_ter(aa, bb)
print(res)
res = mon_add_ter(aa, bb, c = 6, d = 9)
print(res)
res = mon_add_ter(aa, bb, d = 9)
print(res)


resultat: 3+77+1+3=84
resultat: 3+77+6+9=95
resultat: 3+77+1+9=90


Voir uniquement des varibales facultatives.

In [50]:
def mon_add_4(c = 1, d = 3):
    t = c+d
    s = f'resultat: {c}+{d}={t}'
    return s

res = mon_add_4() # ici y'a rien
print(res)


resultat: 1+3=4


# Quelques opérateurs courants:
 * addition soustraction
 * multiplication division division entière
 * puissance
 * opérateur boolean
 
Attention en python 2.X et 3.X la division n'est pas la même!!!!!! c'est mieux en python3.X

In [54]:
a, b, c = 2, 10, 20
r = a + b * c
print(r)


202


In [58]:
a, b = 3, 10
r = b / a
print(r)
r = b // a # division entière
print(r)
print(a % b)

3.3333333333333335
3
3


In [61]:
a = 27.
r = a ** 2
print(r)
r = a ** (1/3)
print(r)

729.0
3.0


# attention opérateur booléan amélioré
and or not

In [63]:

a = True
b = True
res = not(a or b)
print(res)

False


# attention opérateur booléan classique = bit a bit
& | ~

In [65]:
# attention opérateur booléan classique = agit bit a bit
a = 0xff03
b = 0xf003
res = (a & b)
print(hex(res))
res2 = (a | b)
print(hex(res2))

0xf003
0xff03


# Block conditionnel

In [73]:
pval = .00065424
seuil = 0.001

if pval < seuil:
    print('je suis hyper content')
elif pval == seuil:
    print("personne n'en saura rien")
else:
    print("qui m'a piqué mon cyanure")


je suis hyper content


# object list

suite d'éléments hétrogènes.

accessible par index entier.

In [74]:
l = [12, 34., 4, 'lkjlkj' ]
print(l)
print(type(l))


[12, 34.0, 4, 'lkjlkj']
<class 'list'>


In [75]:
l2 = [12, 34.,]  
l3 = l+l2
print(l3)


[12, 34.0, 4, 'lkjlkj', 12, 34.0]


On peut accéder et écrire dans une liste avec son index (zero based)

In [77]:
a = l[1]
print(a)
a = l[3]
print(l)
l[2] = 40
print(l)


34.0
[12, 34.0, 40, 'lkjlkj']
[12, 34.0, 40, 'lkjlkj']


Différent syntax

In [79]:
l = list()
l = []


Ajout d'un élément  à une liste

In [80]:
l = []
l.append(10.)
l.append('yep')
print(l)

[10.0, 'yep']


In [82]:
l3 = l+l+l+l
l3 = l*4
print(l3)


[10.0, 'yep', 10.0, 'yep', 10.0, 'yep', 10.0, 'yep']


# object dict
collections d'élément hétérogène accesible par clef.





In [84]:
d = dict()
d = { }
d = {'a' : 1.,
     'b' : 60, 
     'c' : 'lkjlkj'  }


In [85]:
print(d['a'])
print(d['c'])


1.0
lkjlkj


In [88]:
d['c'] = 50
print(d['c'])
print(d)

50
{'a': 1.0, 'b': 60, 'c': 50}


 on peut ajouter un nouvelle paire clef/valeur

In [89]:
d['x'] = 'youpi'

In [90]:
print(d.keys())

dict_keys(['a', 'b', 'c', 'x'])


In [91]:
print(d.values())

dict_values([1.0, 60, 50, 'youpi'])


# création et importation d'un bibliothèque externe

On peut créer des bibliothèques =module = package de function.
On les utilise avec import.




    # Exercice 1

créer deux fichier:
  * monscript1.py
  * mabibliotheque.py

créer une fonction dans bibliotheque.py

et appeler cette fonction depsui monscript1.py




# Solution 1

# 4 méthodes pour import

In [93]:
# cas 1
import numpy
numpy.zeros(5)


array([0., 0., 0., 0., 0.])

In [95]:
# cas 2
import numpy as np
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [96]:
# cas 3
from numpy import zeros, ones
zeros(5)

array([0., 0., 0., 0., 0.])

In [97]:
# cas 4
from numpy import *
zeros(5)

array([0., 0., 0., 0., 0.])

On peut utiliser un sous module

In [98]:
import scipy.signal
scipy.signal.filtfilt

<function scipy.signal.signaltools.filtfilt(b, a, x, axis=-1, padtype='odd', padlen=None, method='pad', irlen=None)>