---
# Manipulation de ndarray dans numpy
---

# Concatenation de tableau

Tres utile : pour mettre ensemble des datas de sources différentes

syntaxe :

**concatenate([a,b,c],axis)**

**[a,b,c]** est une liste (ou autres iterables) pouvant contenir autant d'élement à concatener que l'on veut

**axis** est la dimension selon laquelle on veut concatener:

par exemple:


In [1]:
import numpy as np

a = np.arange(3)
b = np.arange(5)

c = np.concatenate((a,b)) ### concatene par défault selon la premiere dimension

print(c)

[0 1 2 0 1 2 3 4]


In [2]:
### en multi dimension, on precise axis

a = np.ones((3,4,5))
b = np.ones((3,4,5))

c = np.concatenate((a,b),axis = 0) ### concatene selon la premiere dimension

print(c.shape)

(6, 4, 5)


![Image](./img/np_concat_0.png)

In [3]:
c = np.concatenate((a,b),axis = 1) ### concatene selon la deuxieme dimension

print(c.shape)

(3, 8, 5)


![Image](./img/np_concat_1.png)

In [4]:
### Si les dimensions (autre que celle ou l'on concatène) ne correspondent pas : ça ne marche pas !

a = np.ones((3,4,5))
b = np.ones((3,5,3))

c = np.concatenate((a,b),axis = 1) 

print(c.shape)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 5 and the array at index 1 has size 3

![Image](./img/np_concat_2.png)

###  -> Toutes les dimensions a part celle de l'axis doivent correspondre

# Newaxis

newaxis permet d'ajouter une dimension à un tableau existant. 

Par exemple, un vecteur n'a qu'une seule dimension:

In [5]:
a = np.array(np.arange(10),dtype = 'int64')

print(a)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


Pourtant, si on veut concatener 2 vecteurs pour un faire une matrice a deux colonnes, il faut passer d'un vecteur  (à une seule dimension), à une matrice à une seule colonne:

In [6]:
b = np.array(np.arange(10,20),dtype = 'int64')
print(b)
print(b.shape)

c_1 = np.stack((a,b),axis = 1)
print(c_1)
print(c_1.shape)

c_1 = np.concatenate((a,b),axis = 1)
print(c_1)


### ca marche pour concatener les deux vecteurs dans le sens de la longueur  
#c_0 = np.concatenate((a,b),axis = 0)
#print(c_0)

[10 11 12 13 14 15 16 17 18 19]
(10,)
[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]
(10, 2)


AxisError: axis 1 is out of bounds for array of dimension 1

Pour cela on va utiliser le mot-clé 'newaxis', qui nous permet d'ajouter une nouvelle dimension au tableau

In [7]:
a_bis = a[:,np.newaxis] 

print(a_bis.shape)

(10, 1)



equivalent a 
* a_bis = a.reshape(a.shape[0],1) 
* a_bis = a.reshape(-1,1)
* a_bis = a[:,None]


In [8]:
b_bis = b[:,np.newaxis]
print(b_bis.shape)


(10, 1)


In [9]:
m= np.concatenate((a_bis,b_bis),axis = 1)
# l'axis = 1 existe maintenant
print(m)
print(m.shape)


[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]
(10, 2)


# Operations de réduction: mean/std, max,  sum etc.

Avec le meme principe de 'axis', il est tres facile de reduire un tableau:


 <img src="img/axis.png">

## moyenne 

fonction numpy.mean

#### moyenne des colonnes

In [10]:
m = np.random.randint(20, size = 20).reshape(2,10)

print(m)

##Petit truc pour connaitre l'axis: c'est la dimension qui disparait

mean_m = np.mean(m,axis = 0) 
print(mean_m) ### ici la dimension colonne (2) disparait (on ne garde que les lignes)


[[ 4  4 17 13  2  9  3  9 16 10]
 [13  7 14  8 10  6 11 14 13  9]]
[ 8.5  5.5 15.5 10.5  6.   7.5  7.  11.5 14.5  9.5]


#### moyenne des lignes

In [11]:
mean_m = np.mean(m,axis = 1)
print(m)
print(mean_m) ## ici la dimension des lignes (10) disparait

[[ 4  4 17 13  2  9  3  9 16 10]
 [13  7 14  8 10  6 11 14 13  9]]
[ 8.7 10.5]


#### moyenne du tableau

axis = None

In [12]:
mean_c = np.mean(m,axis = None)
print(m)
print(mean_c)

[[ 4  4 17 13  2  9  3  9 16 10]
 [13  7 14  8 10  6 11 14 13  9]]
9.6


#### écart-type

fonction numpy.std

In [13]:
### ecart type des lignes
std_c_1 = np.std(m,axis = 1)

print(std_c_1)


[5.13906606 2.80178515]


In [14]:
### max des lignes:
max_c_0 = np.max(m,axis = 1)

print(max_c_0)

[17 14]


# Exercice 1: potentiel evoqué moyen
    
- Genérer un signal de 20 signaux (= électrodes) de 10000 points temporels (Gaussien) chacun
    
- Couper ce signal (slice) autour de 10 trigers aleatoires :
    
 trigs = np.array([100,500,2000,2500,3500,4000,6000,7500,8600,9000])
 
en segments de -5 points à +10 points autour de chaque valeur de trig.
(ces 'trigs' correspondent par exemple aux essais dans une condition)
    
- Concatener les données
    
- Calculer la moyenne et la std des 10 trials
    

# Solution 1 avec slice

# Solution 2 avec concatenate

# Operations de tri

## tri des elements

!!! Par defaut le tri s'effectue selon la DERNIERE dimension (axis = -1)


In [18]:
#tri sur le vecteur
c = np.random.randint(low = 100, high = 200, size = 10)
print('c : ', c)

sorted_c = np.sort(c)
print('sorted_c : ', sorted_c)

c :  [120 191 138 187 184 176 187 149 144 111]
sorted_c :  [111 120 138 144 149 176 184 187 187 191]


In [19]:
### tri sur tout le tableau

c = np.random.randint(low = 100, high = 200, size = 15).reshape(3,5)
print(c)

[[123 162 150 170 189]
 [179 162 145 172 194]
 [109 164 127 174 188]]


In [20]:
sorted_c_0 = np.sort(c, axis = 0)
print(sorted_c_0)

[[109 162 127 170 188]
 [123 162 145 172 189]
 [179 164 150 174 194]]


In [21]:
sorted_c_1 = np.sort(c, axis = 1)
print(sorted_c_1)

[[123 150 162 170 189]
 [145 162 172 179 194]
 [109 127 164 174 188]]


### ordre des elements

In [23]:
#autre ex: argsort sur une dimension
#un vecteur trie un autre vecteur


a = np.array([12,22,9,4])
b = np.array(['a','b','c','d'])
print(a)
print(b)
print()

order = np.argsort(a)
print(order)
print(b[order])


[12 22  9  4]
['a' 'b' 'c' 'd']

[3 2 0 1]
['d' 'c' 'a' 'b']


# Exercice 2: max et sort signaux

 * A partir des données de l'exo 1 :
 
signal de 20 cannaux de 10000 points temporels Gaussiens    
segmentés autour de 10 trigs aleatoires entre -5 et +10 points               
concaténés en un tableau (shape = 20*15*10)
moyennés à travers les essais (shape = 20*15)

-> calculer le max des moyennes par cannal
        
-> ordonner les données en fonction de ce max
    


# Solution 2

# Matrix vs. ndarray

Dans numpy, contrairement à Matlab, les operations par defaut se font sur les arrays, et pas sur les matrices.

Il existe un type specialisé pour les matrices, qui sont des tableaux à deux dimensions, et qui disposent d'operations propres aux matrices (inversion, produit, etc.)

## Produit vs. produit matriciel

Par default pour les ndarray, le produit est le produit élement par élement:

In [25]:
import numpy as np

a = np.ones(shape = (4,4))*3
b = np.ones(shape = (4,4))*2

print(a)
print(b)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [26]:
### produit de chaque element

c = a*b 
print(c)



[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [4]:
### produit matriciel (produit scalaire de chaque ligne de a avec chaque colonne de b)
mat_a = np.matrix(a)
mat_b = np.matrix(b)

print(type(mat_a))


<class 'numpy.matrixlib.defmatrix.matrix'>


In [5]:

mat_c = mat_a*mat_b
print(mat_c)
print(type(mat_c))


[[24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]]
<class 'numpy.matrixlib.defmatrix.matrix'>


Il est cependant possible de travailler directement en operation matricielle SANS passer par l'objet np.matrix

In [6]:
c_dot = np.dot(a,b)
print(c_dot)
print(type(c_dot))


[[24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]]
<class 'numpy.ndarray'>


In [33]:
### on peut aussi utiliser la methode de l'objet ndarry dot()

print(a.dot(b))

[[24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]]


In [27]:

#### Depuis python 3 (.5? ou ou.6), operator @ correspond au produit matriciel 
print (a@b)

[[24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]
 [24. 24. 24. 24.]]


### inverse vs. inversion


In [28]:
mat = np.random.randint(1, 5+1, size=(4,4)).astype("float64")

print(mat)


[[5. 1. 4. 5.]
 [2. 3. 2. 5.]
 [5. 3. 4. 3.]
 [2. 5. 2. 4.]]


In [29]:
## on obtient l'inverse de chaque element
un_sur_mat = 1/mat

print(un_sur_mat)

### !!! en matlab c'est l'inverse (/.) a la place de (/)

[[0.2        1.         0.25       0.2       ]
 [0.5        0.33333333 0.5        0.2       ]
 [0.2        0.33333333 0.25       0.33333333]
 [0.5        0.2        0.5        0.25      ]]


In [30]:
## on obtient la matrice inverse
inv_mat = np.linalg.inv(mat)

print(inv_mat)

[[  8.5  -12.    -7.5   10.  ]
 [  0.5   -1.    -0.5    1.  ]
 [-11.75  16.5   10.75 -14.  ]
 [  1.    -1.    -1.     1.  ]]
