# numpy fancy indexing

Numpy permet de manipuler des sous ensemble d'un tableau en lecture/écriture.

Il y a 4 grandes methodes:
  * scalaire
  * par *'slice'*
  * par condition booléene
  * par list d'index



In [1]:
import numpy as np

# reshape

In [2]:
a = np.arange(24) #### equivalent du range, mais pour generer des ndarray
print(a)
print(a.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [6]:

a2 = a.reshape(6,4) ### des lignes de 4 elements, et on a 6 lignes
print(a2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [7]:
a3 = a.reshape(4,2,3)
print(a3.shape)
print(a3)

(4, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


Avec dimension joker= -1

-> la dimension "joker" vaut le "reste" des dimensions restantes

In [8]:
a3 = a.reshape(4,-1,3)
print(a3.shape) ### la dimension par default vaut ici (24/4)/3 = 2



(4, 2, 3)


# Lecture/écriture d'un seul élément

In [9]:
a = np.arange(12).reshape(4,3)
print (a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
# zeros based
# ligne colonne 
e = a[1,1]


print(e)



4


en fait pas vraiment, depent plutot des dimensions que l'on a donné
Dans les visus de ndarray, la derniere dimension apparait toujours le nombre des valeurs comme une ligne (~ colonne), la dimension suivante apparait comme le nombre de lignes  


In [11]:
a[1,2] = 1000
a

array([[   0,    1,    2],
       [   3,    4, 1000],
       [   6,    7,    8],
       [   9,   10,   11]])

# Par slice

![title](img/slice.jpeg)

In [12]:
# ne pas comprendre ça 
# regle du broadcast 
#https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html
b = np.arange(6).reshape(1,6) 
print(b)
c = 10*np.arange(6).reshape(6, 1)
print(c)
a = b + c
print(a)

[[0 1 2 3 4 5]]
[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [13]:
a2 = a[3:, 0:5:2]
a2

array([[30, 32, 34],
       [40, 42, 44],
       [50, 52, 54]])

# Par mask boolean

In [14]:
a = np.random.randn(15)
a

array([ 1.99345024,  0.07453442, -1.84955867,  1.96757442,  0.10002806,
        0.67243868,  0.62117732,  0.36547717,  0.70535   , -0.50430603,
       -1.69182133, -0.80843478, -0.37785041,  0.59053578,  0.14533216])

On peut créer un vecteur de booléen facile, et l'utiliser ensuite pour selectioner un sous ensemble.

In [15]:
keep = (a>0.)
keep
print(keep)
not_keep = ~keep # not en boolean (existe aussi np.logical_not)
print(not_keep)


[ True  True False  True  True  True  True  True  True False False False
 False  True  True]
[False False  True False False False False False False  True  True  True
  True False False]


In [16]:
a3 = a[keep]
a3

array([1.99345024, 0.07453442, 1.96757442, 0.10002806, 0.67243868,
       0.62117732, 0.36547717, 0.70535   , 0.59053578, 0.14533216])

# Selection explicite d'une liste

In [17]:
a = np.arange(7)*10
a

array([ 0, 10, 20, 30, 40, 50, 60])

In [18]:
l = [2, 4, 0]
a2 = a[l]
a2

array([20, 40,  0])

# Attention une slice pointe sur le même tableau!!

Un tableau issue d'un même tableau est une *'view'*.



In [19]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a2 = a[2:-2]
a2[0:6] = np.arange(6)*-10
a2

array([  0, -10, -20, -30, -40, -50])

In [21]:
a


array([  0,   1,   0, -10, -20, -30, -40, -50,   8,   9])


Sinon il faut faire une copie explicite.

In [22]:
a = np.arange(10)
a2 = a[2:-2].copy()
a2[0:6] = np.arange(6)*-10
a2

array([  0, -10, -20, -30, -40, -50])

# Exercice 1

Voici deux vecteurs:
 * a = np.array([10, 20, 30, 40])
 * b = np.array([-.1, -.2, -.3, -.4])

Il faut obtenir avec le jeu des slices l vecteur suivant:
 * c = np.array([10, -.4, 20, -.3, 30, -.2])



In [23]:
a = np.array([10, 20, 30, 40])
b = np.array([-.1, -.2, -.3, -.4])
c = np.array([10, -.4, 20, -.3, 30, -.2])
print(a)
print(b)
print(c)

[10 20 30 40]
[-0.1 -0.2 -0.3 -0.4]
[10.  -0.4 20.  -0.3 30.  -0.2]


# Solution 1

# Exercie 2
Voici un vecteur
a = np.random.randn(5000)
créer un vecteur b qui enlève les déviants.

M + 2.5*std
M - 2.5*std

!!! np.mean(a) pour la moyenne de a
!!! np.std(a) pour l'écart-type de a





# Solution 2

# nan = not a number

In [27]:
a = np.arange(5, dtype='float64')
a[2] = np.nan
a

array([ 0.,  1., nan,  3.,  4.])

In [28]:
b = np.exp(1e40)
b

<ipython-input-28-4f853f65daa7>:1: RuntimeWarning: overflow encountered in exp
  b = np.exp(1e40)


inf

# test : np.isinf et np.isnan




In [29]:
np.isinf(b)

True

In [30]:
np.isnan(a)

array([False, False,  True, False, False])